### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by rspreafico** [dreamRs/shinyWidgets#12]
Congrats for the great package!

I was wondering whether there could be support for tooltips for all widgets, not only the drop-down menu. Popular packages to add tooltips to Shiny, such as bsplus, work only for certain ShinyWidgets (e.g. materialSwitch) but not for others (e.g. pickerInput).

Thanks

**Comment by pvictor** [comment]
Thank you!

It should work now, some widgets were wrap in `htmltools::tagList` which doesn't work with `bsplus::bs_embed_tooltip`, I used `htmltools::tags` instead.

Victor

**Comment by rspreafico** [comment]
Hi Victor,

I tried the latest Github snapshot but I am still getting an error for pickerInput:
```
Error: class is: form-group, needs to be: form-group shiny-input-container
```

Thank you,
Roberto

**Comment by pvictor** [comment]
Sorry for that.

Do you have this error when using `shinyInput_label_embed` ?

I updated `pickerInput`, you can try this example : 

```

library("shiny")
library("shinyWidgets")
library("bsplus")

ui <- fluidPage(
  tags$h2("bsplus tooltip & popover"),
  use_bs_tooltip(),
  use_bs_popover(),
  br(),
  bs_embed_tooltip(
    pickerInput(
      inputId = "p1",
      label = "Test 1",
      choices = rownames(mtcars),
      multiple = TRUE, 
      options = list(`actions-box` = TRUE)
    ),
    title = "I'm a tooltip"
  ),
  br(),
  pickerInput(
    inputId = "p2",
    label = "Test 2",
    choices = rownames(mtcars),
    multiple = TRUE, 
    options = list(`actions-box` = TRUE)
  ) %>%
    shinyInput_label_embed(
      shiny_iconlink() %>%
        bs_embed_popover(title = "pickerInput", content = "An alternative to selectizeInput")
    )
)

server <- function(input, output, session) {
  
}

shinyApp(ui = ui, server = server)

```

Is it that what you try to do ?

I'll look later into other widgets.

Victor

**Comment by rspreafico** [comment]
Hi Victor,

that is exactly what I was trying to do. I downloaded the latest version from Github and it now works nicely with pickerInput. 

Thank you!
Roberto
