### ISSUE TITLE
Disable radioGroupButtons with checkIcon

### ISSUE THREAD

**Issue by benmarchi** [dreamRs/shinyWidgets#311]
This issue is related to #281.

When `checkIcon` is specified for a `radioGroupButtons` disabling the input does not function as expected. Specifically, when the input is disable, it is still possible to change the selection by clicking on the square check box next to the option name. Clicking elsewhere on a button is disabled.

<details><summary>Example app</summary>
<p>

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    
    checkboxGroupButtons(
        inputId = "check",
        choices = head(month.name),
        label = "Check buttons"
    ),
    radioGroupButtons(
        inputId = "radio",
        choices = head(month.name),
        label = "Radio buttons",
        checkIcon = list(
            yes = icon("check-square"),
            no = icon("square-o")
        )
    ),
    
    tags$b("Check"),
    verbatimTextOutput(outputId = "valCheck"),
    tags$b("Radio"),
    verbatimTextOutput(outputId = "valRadio"),
    
    checkboxInput(inputId = "disable", label = "Disable?", value = FALSE),
    checkboxInput(inputId = "disable1", label = "Disable march?", value = FALSE),
    checkboxInput(inputId = "disable2", label = "Disable february & april?", value = FALSE)
)

server <- function(input, output, session) {
    
    output$valCheck <- renderPrint({
        input$check
    })
    output$valRadio <- renderPrint({
        input$radio
    })
    
    observeEvent(input$disable, {
        updateCheckboxGroupButtons(
            session = session, 
            inputId = "check",
            disabled = input$disable
        )
        updateRadioGroupButtons(
            session = session, 
            inputId = "radio",
            disabled = input$disable
        )
    }, ignoreInit = TRUE)
    
    observeEvent(input$disable1, {
        updateCheckboxGroupButtons(
            session = session, 
            inputId = "check",
            disabledChoices = if (input$disable1) "March" else NULL
        )
        updateRadioGroupButtons(
            session = session, 
            inputId = "radio",
            disabledChoices = if (input$disable1) "March" else NULL
        )
    }, ignoreInit = TRUE)
    
    observeEvent(input$disable2, {
        updateCheckboxGroupButtons(
            session = session, 
            inputId = "check",
            disabledChoices = if (input$disable2) c("February", "April") else NULL
        )
        updateRadioGroupButtons(
            session = session, 
            inputId = "radio",
            disabledChoices = if (input$disable2) c("February", "April") else NULL
        )
    }, ignoreInit = TRUE)
    
}

shinyApp(ui = ui, server = server, options = list(launch.browser = TRUE))
```

</p>
</details>

**Comment by pvictor** [comment]
Thanks for reporting that and for the example, it should be fixed on GitHub version.

Victor

**Comment by MokeEire** [comment]
This does not appear to fix the case where a named vector is supplied to choices:

e.g.

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  checkboxGroupButtons(
    inputId = "check",
    choices = set_names(1:6, head(month.name)),
    label = "Check buttons"
  ),
  radioGroupButtons(
    inputId = "radio",
    choices = set_names(1:6, head(month.name)),
    label = "Radio buttons",
    checkIcon = list(
      yes = icon("check-square"),
      no = icon("square-o")
    )
  ),
  
  tags$b("Check"),
  verbatimTextOutput(outputId = "valCheck"),
  tags$b("Radio"),
  verbatimTextOutput(outputId = "valRadio"),
  
  checkboxInput(inputId = "disable", label = "Disable?", value = FALSE),
  checkboxInput(inputId = "disable1", label = "Disable march?", value = FALSE),
  checkboxInput(inputId = "disable2", label = "Disable february & april?", value = FALSE)
)

server <- function(input, output, session) {
  
  output$valCheck <- renderPrint({
    input$check
  })
  output$valRadio <- renderPrint({
    input$radio
  })
  
  observeEvent(input$disable, {
    updateCheckboxGroupButtons(
      session = session, 
      inputId = "check",
      disabled = input$disable
    )
    updateRadioGroupButtons(
      session = session, 
      inputId = "radio",
      disabled = input$disable
    )
  }, ignoreInit = TRUE)
  
  observeEvent(input$disable1, {
    updateCheckboxGroupButtons(
      session = session, 
      inputId = "check",
      disabledChoices = if (input$disable1) 3 else NULL
      # Also tried: "March", set_names(1:6, head(month.name))[3]
    )
    updateRadioGroupButtons(
      session = session, 
      inputId = "radio",
      disabledChoices = if (input$disable1) 3 else NULL
      # Also tried: "March", set_names(1:6, head(month.name))[3]
    )
  }, ignoreInit = TRUE)
  
  observeEvent(input$disable2, {
    updateCheckboxGroupButtons(
      session = session, 
      inputId = "check",
      disabledChoices = if (input$disable2) c(2,4) else NULL
      # Also tried: c("February", "April"), set_names(1:6, head(month.name))[c(2,4)]
    )
    updateRadioGroupButtons(
      session = session, 
      inputId = "radio",
      disabledChoices = if (input$disable2) c(2,4) else NULL 
      # Also tried: c("February", "April"), set_names(1:6, head(month.name))[c(2,4)]
    )
  }, ignoreInit = TRUE)
  
}

shinyApp(ui = ui, server = server, options = list(launch.browser = TRUE))
```

**Comment by pvictor** [comment]
Thanks, that's fixed on GitHub. `disabledChoices` must be a character vector, `disabledChoices = "3"` will work but not `disabledChoices = 3` (with the CRAN version).

Victor
