### ISSUE TITLE
shinyjs reset is not working with shinyWidgets switchInput

### ISSUE THREAD

**Issue by GiCollini** [dreamRs/shinyWidgets#4]
Hi,

shinyjs reset is working for materialSwitch, but it is not working for switchInput.

here an example

```R
library(shiny)
library(shinyjs)
library(shinyWidgets)

#### Server ####
server <- function(input, output){
  
  observeEvent(input$reset_button, {
    shinyjs::reset("checkbox_1")
    shinyjs::reset("switch_1")
    shinyjs::reset("switch_2")
  })
  
  output$checkbox_1_output <- renderPrint({
    input$checkbox_1
  })
  
  output$switch_1_output <- renderPrint({
    input$switch_1
  })
  
  output$switch_2_output <- renderPrint({
    input$switch_2
  })
  
  
}

#### UI ####
ui <- fluidPage(
  useShinyjs(),
  fluidRow(
    column(
      width = 6,
      actionButton(inputId = "reset_button",
                   label = "Reset"),
      hr(),
      verbatimTextOutput("checkbox_1_output"),
      verbatimTextOutput("switch_1_output"),
      verbatimTextOutput("switch_2_output")
    ),
    column(
      width = 6,
      checkboxInput(inputId = "checkbox_1",
                    label = "CHECK",
                    value = F),
      br(),
      switchInput(inputId = "switch_1",
                  Label = "SWITCH 1",
                  value = F),
      br(),
      materialSwitch(inputId = "switch_2",
                     label = "SWITCH 2",
                     value = F,
                     right = T)
    )
  )
  
  
)

#### Run ####
shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hi,
Can you try ? It should be working.

Victor

**Comment by GiCollini** [comment]
Hi,
sorry for the delay..

It still doesn't work for me. I am using the cran version of shinyWidgets.

Gi.

**Comment by pvictor** [comment]
Cool !
I plan to publish to CRAN this week.

Victor
